---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: Instagram
    env: dev
spec:
  selector:
    matchLabels:
      app: Instagram
      env: dev
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      name: myapp
      labels:
        app: Instagram
        env: dev
        version: myapp_v1
    spec:
      containers:
      - name: mycont1
        image: pavanlearningdevops/practicedocker:python
        ports:
        - containerPort: 80
