---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: Instagram
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: Instagram

      
      
